#!/bin/sh
set -e

case "$1" in
    configure)
        # Update icon cache
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
        fi
        
        # Update desktop database
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database -q || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
